baseurl = "http://blog.marrama.com/"
languageCode = "en-us"
title = "A Man, a Van, and a Plan"

[Params]
Author = "Joe Marrama"
subtitle = "Climbing, adventuring, and everything in between"
copyright = "Words by Joe Marrama"
analytics = "UA-38972479-1"

[taxonomies]
tag = "tags"
